version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
      - echo Listing contents of current directory...
      - ls -R
      - echo Listing contents of dist directory...
      - ls -R dist

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes
